### ISSUE TITLE
no output with clipping mask

### ISSUE THREAD

**Issue by MatthewAlner** [Pixofield/keyshape-lottie-format#4]
I have made a keyshape animation the uses a clipping mask but I get no output when using the preview tool on lottiefiles.com

<img width="816" alt="Screenshot 2019-05-07 08 38 33" src="https://user-images.githubusercontent.com/2782730/57281841-b2028300-70a3-11e9-8aae-3246b45963b6.png">

here is the `.keyshape` file and the `.json` that gets exported using the latest release

[Archive.zip](https://github.com/Pixofield/keyshape-lottie-format/files/3151314/Archive.zip)

**Comment by MatthewAlner** [comment]
🤷‍♂ maybe its not the clipping, I tried removing it and it still didn't work, I also tired removing the scale animations

**Comment by Pixofield** [comment]
The main issue why it doesn't show anything is the ellipse stroke widths, which are not exported correctly. You can get it to export correctly by changing the stroke widths of the ellipses in Keyshape (there's four ellipses in that animation). After that, Lottie will play back the animation. This is definitely a bug. There will be a new version of the Lottie plugin in the coming weeks and this bug will be fixed in it.

Another issue is the mask animation, which won't display correctly. Animating the content of a mask isn't supported by Keyshape and its Lottie exporter. If you know that the background will always be white, a workaround would be to create a large white rectangle with a hole to show a portion of the record.

**Comment by MatthewAlner** [comment]
Thanks for getting back to me, I will give your suggestions a go 😄

**Comment by MatthewAlner** [comment]
Great got it working with the workarounds you suggested, thanks again.

**Comment by bobeczech** [comment]
Is this fixed already? Cuz it makes Keyshape kinda useless for me :((

**Comment by Pixofield** [comment]
The bug about the ellipse stroke widths has been fixed. If you have found some other issues, then please open a new issue with details about it.
